app:
  build: ./app
  restart: always
  environment:
    DEBUG: 'false'
  expose:
    - 8000
  volumes:
    - /code/static

nginx:
  build: ./nginx
  restart: always
  ports:
    - 127.0.0.1:5000:80
  links:
    - app
  volumes_from:
    - app
