mongo:
  build: ./mongo
  command: --smallfiles --storageEngine wiredTiger
  restart: always
  expose:
    - 27017

app:
  build: ./app
  restart: always
  environment:
    MONGODB_HOST: mongo
    MONGODB_PORT: 27017
    DEBUG: true
  expose:
    - 8000
  links:
    - mongo
  volumes:
    - /code/static

nginx:
  build: ./nginx
  restart: always
  ports:
    - 5000:80
  links:
    - app
  volumes_from:
    - app
