services:
  app:
    build: ./app
    restart: always
    environment:
      DEBUG: "false"
    expose:
      - 8000
    volumes:
      - static_data:/code/static

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "127.0.0.1:5000:80"
    depends_on:
      - app
    volumes:
      - static_data:/code/static

volumes:
  static_data:
