# encoding=utf-8

intros = 'intro', [
    {'text': u'Achtung'},
    {'text': u'Die neue Gefahr'},
    {'text': u'Endlich'},
    {'text': u'Entlarvt'},
    {'text': u'Hilfe'},
    {'text': u'Horror'},
    {'text': u'Schock'},
    {'text': u'Skandal'},
    {'text': u'Wir decken auf:'},
]

# Rules: Capitalize, use pural form
adjectives = 'adjective', [
    {'text': u'Böse'},
    {'text': u'Deutsche'},
    {'text': u'Fette'},
    {'text': u'Fiese'},
    {'text': u'Gefährliche'},
    {'text': u'Hässliche'},
    {'text': u'Notgeile'},
    {'text': u'Obszöne'},
    {'text': u'Pädophile'},
    {'text': u'Schwule'},
    {'text': u'Unfähige'},
    {'text': u'Vogelfreie'},
]

prefixes = 'prefix', [
    {'text': u'AHV'},
    {'text': u'Atom'},
    {'text': u'Ausländer'},
    {'text': u'Balkan'},
    {'text': u'Banken'},
    {'text': u'Casino'},
    {'text': u'Chaos'},
    {'text': u'Gewinnspiel'},
    {'text': u'Griechen'},
    {'text': u'Hanf'},
    {'text': u'Horror'},
    {'text': u'Inkasso'},
    {'text': u'IV'},
    {'text': u'Käse'},
    {'text': u'Killer'},
    {'text': u'Mafia'},
    {'text': u'Militär'},
    {'text': u'Ostblock'},
    {'text': u'Pädo'},
    {'text': u'Peitschen'},
    {'text': u'Penner'},
    {'text': u'Pfeiffen'},
    {'text': u'Playboy'},
    {'text': u'Porno'},
    {'text': u'Psycho'},
    {'text': u'Roma'},
    {'text': u'Rotlicht'},
    {'text': u'Sex'},
    {'text': u'Skandal'},
    {'text': u'Sozialhilfe'},
    {'text': u'Star'},
    {'text': u'Suizid'},
    {'text': u'Terror'},
    {'text': u'UBS'},
    {'text': u'Volks'},
    {'text': u'Wunder'},
]

# Rules: Suffix must be the subject of the sentence, an actor
# Case must be one of the following:
# m: Männlich, w: Weiblich, s: Sächlich, p: Plural
suffixes = 'suffix', [
    {'text': u'Aktivist', 'case': u'm'},
    {'text': u'Ali', 'case': u'm'},
    {'text': u'Alki', 'case': u'm'},
    {'text': u'Anwalt', 'case': u'm'},
    {'text': u'Arbeitsloser', 'case': u'm'},
    {'text': u'Asylbewerber', 'case': u'm'},
    {'text': u'Bäcker', 'case': u'm'},
    {'text': u'Banker', 'case': u'm'},
    {'text': u'Berlusconi', 'case': u'm'},
    {'text': u'Blocher', 'case': u'm'},
    {'text': u'Boss', 'case': u'm'},
    {'text': u'Bschiisser', 'case': u'm'},
    {'text': u'Bundesrat', 'case': u'm'},
    {'text': u'Chef', 'case': u'm'},
    {'text': u'Demonstranten', 'case': u'p'},
    {'text': u'Doktor', 'case': u'm'},
    {'text': u'Ehemann', 'case': u'm'},
    {'text': u'Frau', 'case': u'w'},
    {'text': u'Fürst', 'case': u'm'},
    {'text': u'Gaddaffi', 'case': u'm'},
    {'text': u'Gangster', 'case': u'm'},
    {'text': u'Grüsel', 'case': u'm'},
    {'text': u'Hasser', 'case': u'm'},
    {'text': u'Hauswart', 'case': u'm'},
    {'text': u'Kapitän', 'case': u'm'},
    {'text': u'Killer', 'case': u'm'},
    {'text': u'Kind', 'case': u's'},
    {'text': u'Mann', 'case': u'm'},
    {'text': u'Merkel', 'case': u'w'},
    {'text': u'Metzger', 'case': u'm'},
    {'text': u'Migrant', 'case': u'm'},
    {'text': u'Nazi', 'case': u'm'},
    {'text': u'Neonazis', 'case': u'm'},
    {'text': u'Nerd', 'case': u'm'},
    {'text': u'Peer', 'case': u'm'},
    {'text': u'Plagiator', 'case': u'm'},
    {'text': u'Raser', 'case': u'm'},
    {'text': u'Rentner', 'case': u'm'},
    {'text': u'Trottel', 'case': u'm'},
    {'text': u'Tschutter', 'case': u'm'},
    {'text': u'Ueli', 'case': u'm'},
    {'text': u'Ylmaz', 'case': u'm'},
    {'text': u'Zocker', 'case': u'm'},
]

# Rules: Action must be provided both in singular and plural form, may be empty
actions = 'action', [
    {'action_s': u'', 'action_p': u'', 'text': u'auf diebestour'},
    {'action_s': u'', 'action_p': u'', 'text': u'aufgedeckt'},
    {'action_s': u'', 'action_p': u'', 'text': u'ausgeschafft'},
    {'action_s': u'', 'action_p': u'', 'text': u'entlarvt'},
    {'action_s': u'', 'action_p': u'', 'text': u'gehängt'},
    {'action_s': u'', 'action_p': u'', 'text': u'im Komma'},
    {'action_s': u'', 'action_p': u'', 'text': u'im Liebestaumel'},
    {'action_s': u'', 'action_p': u'', 'text': u'in Psychiatrie eingeliefert'},
    {'action_s': u'', 'action_p': u'', 'text': u'in Untersuchungshaft'},
    {'action_s': u'', 'action_p': u'', 'text': u'knapp am Tod vorbei'},
    {'action_s': u'', 'action_p': u'', 'text': u'nackt abgekratzt'},
    {'action_s': u'', 'action_p': u'', 'text': u'tot'},
    {'action_s': u'', 'action_p': u'', 'text': u'voll daneben'},
    {'action_s': u'', 'action_p': u'', 'text': u'von Motorboot zerfetzt'},
    {'action_s': u'ärgert', 'action_p': u'ärgern', 'text': u'sich über Nacktvideo'},
    {'action_s': u'belästigt', 'action_p': u'belästigen', 'text': u'Mädchen'},
    {'action_s': u'gewinnt', 'action_p': u'gewinnen', 'text': u''},
    {'action_s': u'hört', 'action_p': u'hören', 'text': u'gern DJ Bobo'},
    {'action_s': u'ist', 'action_p': u'sind', 'text': u'zu dick'},
    {'action_s': u'klaut', 'action_p': u'klauen', 'text': u'Guezli in der Migros'},
    {'action_s': u'läuft', 'action_p': u'laufen', 'text': u'Amok'},
    {'action_s': u'lobt', 'action_p': u'loben', 'text': u'Justin Bieber'},
    {'action_s': u'stürmt', 'action_p': u'stürmen', 'text': u'Primarschule'},
    {'action_s': u'tritt', 'action_p': u'treten', 'text': u'zurück'},
    {'action_s': u'will', 'action_p': u'wollen', 'text': u'Staat enteignen'},
    {'action_s': u'zockt', 'action_p': u'zocken', 'text': u'ab'},
]


# Register all collections in here that you want to load
collections = [intros, adjectives, prefixes, suffixes, actions]
